name: Test extractor function
on:
  # 触发方式: 手动触发和推送 mater 分支时触发
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  download_from_gdrive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install gdrive tool
      run: |
        curl -L -o gdrive.tar.gz https://github.com/glotlabs/gdrive/releases/download/3.9.1/gdrive_linux-x64.tar.gz
        tar -xzf gdrive.tar.gz
        sudo install gdrive /usr/local/bin/gdrive

    - name: Setup service account credentials
      run: |
        echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT_SECRET }}" > secret.json
        echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT_TOKENS }}" > tokens.json
        tar -cf gdrive_export.tar secret.json tokens.json

    - name: Authenticate with Google Drive
      run: |
        gdrive account import ./gdrive_export.tar

    # - name: Download files list
    #   run: |
    #     FILE_IDS=()
    #     for FILE_ID in "${FILE_IDS[@]}"
    #     do
    #       echo "Downloading $FILE_ID ..."
    #       gdrive download "$FILE_ID"
    #     done

    # Download folder
    # - name: Download folder from Google Drive
    #   run: |
    #     FILE_ID="1df-sCx8eXkaxV1fiUoos6shYxBg0H_Do" # Curse of Pleasure v0.9
    #     gdrive download --path ./gdrive-data "$FOLDER_ID"

    # Download file and extract
    - name: Download file from Google Drive
      run: |
        FILE_ID="14WIwqL2D0HfRA49lf_Q6VzMniS9Q14Kr" # "Curse of pleasure v0.9.tar.gz"
        gdrive download --path ./gdrive-data "$FOLDER_ID"

    - name: Run test
      run: |
        echo -e "Enter run test."