name: Test extractor function
on:
  # 触发方式: 手动触发和推送 mater 分支时触发
  workflow_dispatch:
  push:
    branches: [master]

env:
  DOWNLOAD_FOLDER: "gdrive_data"

jobs:
  download_from_gdrive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install gdrive tool
      run: |
        curl -L -o gdrive.tar.gz https://github.com/glotlabs/gdrive/releases/download/3.9.1/gdrive_linux-x64.tar.gz
        tar -xzf gdrive.tar.gz
        sudo install gdrive /usr/local/bin/gdrive

    - name: Setup service account credentials
      run: |
        dirName=${{ secrets.GDRIVE_SERVICE_ACCOUNT_NAME }}
        mkdir ${dirName}
        echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT_SECRET }}" | base64 --decode > ${dirName}/secret.json
        echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT_TOKENS }}" | base64 --decode > ${dirName}/tokens.json
        tar -cf gdrive_export.tar ${dirName}
        rm -rf ${dirName}

    - name: Authenticate with Google Drive
      run: |
        gdrive account import ./gdrive_export.tar

    - name: Make download folder
      run: mkdir ${{ env.DOWNLOAD_FOLDER }}

    # - name: Download files list
    #   run: |
    #     FILE_IDS=()
    #     for FILE_ID in "${FILE_IDS[@]}"
    #     do
    #       echo "Downloading $FILE_ID ..."
    #       gdrive files download "$FILE_ID" --destination ${{ env.DOWNLOAD_FOLDER }}
    #     done

    # Download folder
    # - name: Download folder from Google Drive
    #   run: |
    #     FOLDER_ID="1df-sCx8eXkaxV1fiUoos6shYxBg0H_Do"
    #     gdrive files download --recursive --destination ${{ env.DOWNLOAD_FOLDER }} "$FOLDER_ID"

    # Download compressed data and extract
    - name: Download file from Google Drive
      run: |
        FILE_ID="14WIwqL2D0HfRA49lf_Q6VzMniS9Q14Kr" # "Curse of pleasure v0.9.tar.gz"
        gdrive files download ${FILE_ID} --destination ${{ env.DOWNLOAD_FOLDER }}

    - name: Run test
      run: |
        echo -e "Enter run test."