name: Test extractor function
on:
  # 触发方式: 手动触发和推送 mater 分支时触发
  workflow_dispatch:
  push:
    branches: [master]

env:
  # slice repo name from repo full path
  REPO_NAME: "$(echo ${{ github.repository }} | cut -d'/' -f2)"
  REPO_FOLDER: "${{ github.workspace }}"

jobs:
  download_from_gdrive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install gdrive tool
      working-directory: ./
      run: |
        curl -L -o gdrive.tar.gz https://github.com/glotlabs/gdrive/releases/download/3.9.1/gdrive_linux-x64.tar.gz
        tar -xzf gdrive.tar.gz
        sudo install gdrive /usr/local/bin/gdrive

    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Prepare environment
      working-directory: ${{ env.REPO_FOLDER }}
      run: pip install -r requirements.txt

    - name: Setup service account credentials
      working-directory: ./
      run: |
        dirName=${{ secrets.GDRIVE_SERVICE_ACCOUNT_NAME }}
        mkdir ${dirName}
        echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT_SECRET }}" | base64 --decode > ${dirName}/secret.json
        echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT_TOKENS }}" | base64 --decode > ${dirName}/tokens.json
        tar -cf gdrive_export.tar ${dirName}
        rm -rf ${dirName}

    - name: Authenticate with Google Drive
      working-directory: ./
      run: |
        gdrive account import ./gdrive_export.tar

    - name: Create folders
      working-directory: ./
      run: |
        mkdir -p ${{ runner.workspace }}/gdrive_data
        mkdir -p ${{ runner.workspace }}/extract_data

    # - name: Download files list
    #   run: |
    #     FILE_IDS=()
    #     for FILE_ID in "${FILE_IDS[@]}"
    #     do
    #       echo "Downloading $FILE_ID ..."
    #       gdrive files download "$FILE_ID" --destination ${{ env.DOWNLOAD_FOLDER }}
    #     done

    # Download folder
    # - name: Download folder from Google Drive
    #   run: |
    #     FOLDER_ID="1df-sCx8eXkaxV1fiUoos6shYxBg0H_Do"
    #     gdrive files download --recursive --destination ${{ env.DOWNLOAD_FOLDER }} "$FOLDER_ID"

    # Download compressed data and extract
    - name: Download file from Google Drive
      id: download_and_extract
      working-directory: ./
      run: |
        FILE_INFO=(
          "14WIwqL2D0HfRA49lf_Q6VzMniS9Q14Kr:Curse of pleasure v0.9.tar.gz"
        )
        EXTRACTED_FOLDERS=()
        DOWNLOAD_DIR="${{ runner.workspace }}/gdrive_data"

        for item in "${FILE_INFO[@]}"
        do
          FILE_ID="${item%%:*}"
          FILENAME="${item#*:}"

          gdrive files download "${FILE_ID}" --destination "${DOWNLOAD_DIR}"

          echo "Extracting \"${FILENAME}\"..."
          # Extract and find the top-level directory created
          # Try to extract as a tar archive, letting tar auto-detect compression
          EXTRACTED_DIR=$(tar -tf "${DOWNLOAD_DIR}/${FILENAME}" 2>/dev/null | head -1 | cut -f1 -d"/")
          tar -xf "${DOWNLOAD_DIR}/${FILENAME}" -C "${DOWNLOAD_DIR}"

          EXTRACTED_FOLDERS+=("${DOWNLOAD_DIR}/${EXTRACTED_DIR}")
        done

        echo "extracted_folder=${EXTRACTED_FOLDERS[*]}" >> ${GITHUB_OUTPUT}

    - name: Run test
      working-directory: ${{ env.REPO_FOLDER }}
      run: |
        extract_folder='${{ steps.download_and_extract.outputs.extracted_folder }}'
        for folder in ${extract_folder}
        do
          game_name=$(basename "${folder}")
          echo "Processing game ${game_name}..."
          python run.py --dataFolder ${folder} --outputFolder "${{ runner.workspace }}/extract_data" --title ${game_name}
        done